DB_USERNAME = "USERNAME"
DB_PASSWORD = "PASSWORD"
DB_PORT = "PORT"
DB_HOST = "HOST"
DB_NAME = "DB"
DB_DRIVER_NAME = "DRIVER_NAME"

CACHE_PASSWORD = "PASSWORD"
CACHE_PORT = "PORT"
CACHE_HOST = "HOST"

ASSET_CLOUD_NAME = "CLOUD_NAME"
ASSET_API_KEY = "API_KEY"
ASSET_API_SECRET = "API_SECRET"

LOG_INFO = "INFO"
LOG_ERRORS = "ERRORS"



CONFIG_SECTION_DATABASE = "DATABASE"
CONFIG_SECTION_CACHE = "REDIS"
CONFIG_SECTION_ASSET = "CLOUDINARY"
CONFIG_SECTION_LOG = "LOGS"

DB_TYPE_MSSQL_SERVER = "MSSQLSERVER"
DB_TYPE_MYSQL_SERVER = "MYSQLSERVER"
DB_TYPE_ORACLE = "ORACLE"
DB_TYPE_POSTGRESQL = "POSTGRESQL"